import XCTest
@testable import DriftLogic

/// Golden-master verification: the Swift engine must reproduce the verified web
/// engine's output for ALL 4,860 condition combinations.
///
/// `golden.json` was generated by running the live rockyriversteelhead.com embed
/// engine (June 2026, post pro-tip fix) across every scenario.
///
/// Known intentional divergences from the web engine:
///  1. HTML entities are decoded to Unicode in Swift (&ndash; → –, &mdash; → —,
///     &amp; → &, &deg; → °). The test decodes the golden strings the same way.
///  2. The web engine has a bug where current == "still" renders the literal
///     string "undefined" in the Flow row of "Why This Rig". The Swift engine
///     ships real copy instead; the test substitutes it before comparing.
final class GoldenMasterTests: XCTestCase {

    // MARK: Golden JSON shapes

    private struct GoldenScenario: Decodable {
        let method, species, current, depth, temp, clarity: String
        let hatch: String?
    }
    private struct GoldenPick: Decodable { let n: String; let x: String }
    private struct GoldenWhy: Decodable { let hl: String; let rows: [[String]] }
    private struct GoldenEntry: Decodable {
        let s: GoldenScenario
        let rig: [[String]]
        let picks: [GoldenPick]
        let why: GoldenWhy
        let proTip: String
        let vids: [String]
    }

    private static let stillFlowCopy =
        "Still, frog-water sections — fish it like a pond: cover water methodically and let the fish tell you the pace."

    private func decodeEntities(_ s: String) -> String {
        s.replacingOccurrences(of: "&ndash;", with: "–")
         .replacingOccurrences(of: "&mdash;", with: "—")
         .replacingOccurrences(of: "&deg;", with: "°")
         .replacingOccurrences(of: "&amp;", with: "&")
    }

    private func loadGolden() throws -> [GoldenEntry] {
        let bundle = Bundle(for: GoldenMasterTests.self)
        guard let url = bundle.url(forResource: "golden", withExtension: "json") else {
            XCTFail("golden.json missing from test bundle — check the DriftLogicTests target resources")
            return []
        }
        return try JSONDecoder().decode([GoldenEntry].self, from: Data(contentsOf: url))
    }

    private func scenario(from g: GoldenScenario) throws -> Scenario {
        func req<T: RawRepresentable>(_ raw: String, _ type: T.Type) throws -> T where T.RawValue == String {
            guard let v = T(rawValue: raw) else {
                throw NSError(domain: "golden", code: 1,
                              userInfo: [NSLocalizedDescriptionKey: "bad raw value \(raw) for \(type)"])
            }
            return v
        }
        return Scenario(
            method: try req(g.method, Method.self),
            species: try req(g.species, Species.self),
            current: try req(g.current, CurrentSpeed.self),
            depth: try req(g.depth, WaterDepth.self),
            temp: try req(g.temp, WaterTemp.self),
            clarity: try req(g.clarity, WaterClarity.self),
            hatch: g.hatch.map { raw in
                guard let h = Hatch(rawValue: raw) else {
                    XCTFail("bad hatch raw value \(raw)"); return Hatch.none
                }
                return h
            }
        )
    }

    func testAllScenariosMatchGoldenMaster() throws {
        let golden = try loadGolden()
        XCTAssertEqual(golden.count, 4860, "expected the full scenario sweep")

        var failures = 0
        func check(_ cond: Bool, _ msg: @autoclosure () -> String) {
            if !cond {
                failures += 1
                if failures <= 25 { XCTFail(msg()) } // cap log spam; count everything
            }
        }

        for entry in golden {
            let s = try scenario(from: entry.s)
            let r = DriftLogicEngine.recommend(for: s)
            let tag = "[\(entry.s.method)/\(entry.s.species)/\(entry.s.current)/\(entry.s.depth)/\(entry.s.temp)/\(entry.s.clarity)/\(entry.s.hatch ?? "nil")]"

            // Rig: 3 rows
            check(r.rig.count == 3, "\(tag) rig rows \(r.rig.count)")
            for (i, row) in entry.rig.enumerated() where i < r.rig.count {
                check(r.rig[i].label == decodeEntities(row[0]), "\(tag) rig[\(i)] label: \(r.rig[i].label) ≠ \(decodeEntities(row[0]))")
                check(r.rig[i].value == decodeEntities(row[1]), "\(tag) rig[\(i)] value: \(r.rig[i].value) ≠ \(decodeEntities(row[1]))")
            }

            // Picks: 5, unique, exact text
            check(r.picks.count == 5, "\(tag) picks \(r.picks.count)")
            check(Set(r.picks.map(\.name)).count == r.picks.count, "\(tag) duplicate picks")
            for (i, p) in entry.picks.enumerated() where i < r.picks.count {
                check(r.picks[i].name == decodeEntities(p.n), "\(tag) pick[\(i)] name: \(r.picks[i].name) ≠ \(decodeEntities(p.n))")
                check(r.picks[i].note == decodeEntities(p.x), "\(tag) pick[\(i)] note: \(r.picks[i].note) ≠ \(decodeEntities(p.x))")
            }

            // Why: headline + 4 rows (with the documented "still" substitution)
            check(r.why.headline == decodeEntities(entry.why.hl), "\(tag) why.hl: \(r.why.headline) ≠ \(decodeEntities(entry.why.hl))")
            check(r.why.rows.count == 4, "\(tag) why rows \(r.why.rows.count)")
            for (i, row) in entry.why.rows.enumerated() where i < r.why.rows.count {
                var expected = decodeEntities(row[1])
                if entry.s.current == "still", expected.hasPrefix("undefined") {
                    expected = expected.replacingOccurrences(of: "undefined", with: Self.stillFlowCopy)
                }
                check(r.why.rows[i].label == decodeEntities(row[0]), "\(tag) why[\(i)] label: \(r.why.rows[i].label) ≠ \(decodeEntities(row[0]))")
                check(r.why.rows[i].value == expected, "\(tag) why[\(i)] value: \(r.why.rows[i].value) ≠ \(expected)")
            }

            // Pro tip
            check(r.proTip == decodeEntities(entry.proTip), "\(tag) proTip: \(r.proTip) ≠ \(decodeEntities(entry.proTip))")

            // Videos: 5, unique, exact IDs in order
            check(r.videoIDs.count == 5, "\(tag) vids \(r.videoIDs.count)")
            check(Set(r.videoIDs).count == r.videoIDs.count, "\(tag) duplicate videos")
            check(r.videoIDs == entry.vids, "\(tag) vids: \(r.videoIDs) ≠ \(entry.vids)")
        }

        XCTAssertEqual(failures, 0, "total golden-master mismatches: \(failures)")
    }

    // MARK: Domain rules carried over from dl_harness.js

    func testFlyMethodNeverRecommendsHardwareOrBait() throws {
        let hardware = try NSRegularExpression(
            pattern: "spoon|cleo|spinnerbait|chatterbait|crankbait|square-?bill|stickbait|jerkbait|rapala|husky jerk|ned rig|drop-shot|blade bait|chicken liver|cut bait|night ?crawler|stink|punch bait|dip bait|kwikfish|mag lip|\\bplug\\b",
            options: [.caseInsensitive])
        for entry in try loadGolden() where entry.s.method == "fly" {
            let s = try scenario(from: entry.s)
            for p in DriftLogicEngine.recommend(for: s).picks {
                let range = NSRange(p.name.startIndex..., in: p.name)
                XCTAssertNil(hardware.firstMatch(in: p.name, range: range).map { _ in p.name },
                             "fly pick contains hardware/bait: \(p.name)")
            }
        }
    }

    func testProTipsAreMethodAware() throws {
        // Regression for the June 6 web fix: smallmouth fly/pin must not get spinning advice.
        for method in [Method.fly, .pin] {
            let s = Scenario(method: method, species: .smallmouth, current: .moderate,
                             depth: .mid, temp: .prime, clarity: .clear, hatch: nil)
            let tip = DriftLogicEngine.recommend(for: s).proTip.lowercased()
            XCTAssertFalse(tip.contains("ned rig") || tip.contains("drop-shot"),
                           "\(method.rawValue) smallmouth pro tip gives spinning advice: \(tip)")
        }
    }

    func testEveryPickHasCuratedAmazonQuery() throws {
        // Pick names are rig descriptions, not product names — uncurated searches
        // return towable boat tubes, WD-40 oil, etc. Every pick the engine can
        // produce must have a hand-written Amazon query.
        var names = Set<String>()
        for entry in try loadGolden() {
            for p in entry.picks { names.insert(decodeEntities(p.n)) }
        }
        let missing = names.filter { ShopLinks.amazonSearchOverrides[$0] == nil }
        XCTAssertTrue(missing.isEmpty, "picks without a curated Amazon query: \(missing.sorted())")
    }

    func testRigRowsAlwaysOfferShopLinks() throws {
        // Every rod/reel row should offer the three price tiers; line/leader/
        // tippet/float rows a single link.
        for entry in try loadGolden().prefix(300) {
            let s = try scenario(from: entry.s)
            for row in DriftLogicEngine.recommend(for: s).rig {
                let options = RigShopLinks.options(forRowLabel: row.label, method: s.method, rowValue: row.value)
                XCTAssertFalse(options.isEmpty, "rig row '\(row.label)' (\(s.method.rawValue)) has no shop links")
                for o in options {
                    XCTAssertTrue(o.url.absoluteString.hasPrefix("https://www.amazon.com/s?k="), "bad rig URL: \(o.url)")
                    XCTAssertTrue(o.url.absoluteString.contains("tag=rockyriver-20"), "missing Associates tag: \(o.url)")
                }
            }
        }
    }

    func testShopURLsAreWellFormed() throws {
        for entry in try loadGolden().prefix(500) {
            let s = try scenario(from: entry.s)
            for p in DriftLogicEngine.recommend(for: s).picks {
                let amazon = ShopLinks.amazonURL(for: p.name).absoluteString
                XCTAssertTrue(amazon.hasPrefix("https://www.amazon.com/s?k="), "bad amazon URL: \(amazon)")
                let fishUSA = ShopLinks.fishUSAURL(for: p.name).absoluteString
                XCTAssertTrue(fishUSA.hasPrefix("https://www.fishusa.com/"), "bad FishUSA URL: \(fishUSA)")
            }
        }
    }
}
